kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: akhila
  annotations:
    kubernetes.io/created-by: 'akhila'
    jenkins.build.url: 'https://jenkins.daws78s.online/expense/job/backend/46'
spec:
  containers:
  - name: nginx
    image: nginx